[project]
name = "nebuladance"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.0"
dependencies = [
    "opencv-python-headless>=4.12.0.88",
    "pyinstaller>=6.14.2",
    "pyside6>=6.9.1",
]
